volumes:
  db_data_volume: { }

services:
  tlh:
    image: tlh/tlh-server
    build:
      context: ./html
    ports:
      - "127.0.0.1:8067:80"
  db:
    image: mariadb:10.2
    restart: always
    ports:
      - "127.0.0.1:3406:3306"
    volumes:
      - type: volume
        source: db_data_volume
        target: /var/lib/mysql
      - type: bind
        source: ./sql_inits/
        target: /docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=abcd
      - MYSQL_DATABASE=hpm
